# Generated by Django 4.0.5 on 2022-06-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('Precio_producto', models.CharField(max_length=5, verbose_name='Precio del producto')),
                ('Descripcion_producto', models.CharField(max_length=150, verbose_name='Descripcion del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_usuario', models.CharField(max_length=15, verbose_name='Nombre de usuario')),
                ('Password_usuario', models.CharField(max_length=10, verbose_name='Password del usuario')),
            ],
        ),
    ]
