# Generated by Django 4.0.5 on 2022-06-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0002_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Descripcion_producto',
            field=models.TextField(max_length=150, verbose_name='Descripcion del producto'),
        ),
    ]
