# Generated by Django 4.0.5 on 2022-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0005_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Tiendita/vitrina'),
        ),
    ]
