# Generated by Django 4.0.5 on 2022-06-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Foto',
            new_name='Foto_producto',
        ),
    ]
